/**
 * general errors handle
 */
export const MESSAGE_FROM_API = "MESSAGE_FROM_API";
export const RESET_MESSAGES = "RESET_MESSAGES";

/**
 * authentication handles
 */
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER_INFO = "UPDATE_USER_INFO";
export const UPDATE_OWNER_INFO = "UPDATE_OWNER_INFO";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const SET_SENDING_STATUS = "SET_SENDING_STATUS";
export const WELCOME_MESSAGE = "WELCOME_MESSAGE";

/**
 * community handles
 */
export const GET_MY_COMMUNITIES = "GET_MY_COMMUNITIES";
export const ACTIVATE_COMMUNITY = "ACTIVATE_COMMUNITY";
export const DEACTIVATE_COMMUNITY = "DEACTIVATE_COMMUNITY";
export const DELETE_COMMUNITY = "DELETE_COMMUNITY";
export const ACTIVATE_MULTI_COMMUNITY = "ACTIVATE_MULTI_COMMUNITY";
export const DEACTIVATE_MULTI_COMMUNITY = "DEACTIVATE_MULTI_COMMUNITY";
export const DELETE_MULTI_COMMUNITY = "DELETE_MULTI_COMMUNITY";

export const PICK_COMMUNITY = "PICK_COMMUNITY";
export const PICK_MULTI_COMMUNITY = "PICK_MULTI_COMMUNITY";
export const SET_BILLING_INFO = "SET_BILLING_INFO";
export const CLEAR_BILLING_INFO = "CLEAR_BILLING_INFO";
export const CLEAR_LAST_INVOICE = "CLEAR_LAST_INVOICE";
export const SET_STT_SET_CARD = "SET_STT_SET_CARD";
export const SET_STT_SENDING = "SET_STT_SENDING";
export const SET_STT_READY = "SET_STT_READY";
export const SET_STT_HIDE = "SET_STT_HIDE";
export const SET_DIALOG_TITLE = "SET_DIALOG_TITLE";

export const SHOW_ACT_DLG = "SHOW_ACT_DLG";
export const ACTIVATING = "ACTIVATING";
export const ACTIVE_STATUS = "ACTIVE_STATUS";
export const DEACTIVATING = "DEACTIVATING";

export const COUPON_VERIFIED = "COUPON_VERIFIED";
export const CLEAR_COUPON_STATUS = "CLEAR_COUPON_STATUS";
export const GET_PLAN = "GET_PLAN";

/**
 * search results
 */
export const SEARCH_CRITERIA = "SEARCH_CRITERIA";
export const SET_SEARCH_FILTER = "SET_SEARCH_FILTER";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const SORT_ORDER = "SORT_ORDER";
export const SET_PICKING = "SET_PICKING";
export const VIEW_COMMUNITY = "VIEW_COMMUNITY";
export const CLEAR_FILTER_MASK = "CLEAR_FILTER_MASK";
export const CLEAR_CRITERIA = "CLEAR_CRITERIA";
export const SEARCHING = "SEARCHING";
export const SET_BACK_URL = "SET_BACK_URL";
export const GET_OWNERS = "GET_OWNERS";
export const CLEAR_OWNERS = "CLEAR_OWNERS";
